server:
  port: 8080
  host: "0.0.0.0"
  cors_enabled: true

nats:
  url: "nats://localhost:4222"
  jetstream:
    enabled: false  # Disable for now since we may not have NATS running
    retention_days: 7

database:
  path: "./data/hexarag.db"
  migrations_path: "./internal/adapters/storage/sqlite/migrations"

llm:
  provider: "openai-compatible"
  base_url: "http://localhost:11434/v1"  # Ollama default
  api_key: "dummy"
  model: "llama2"
  max_tokens: 4096
  temperature: 0.7

tools:
  mcp_time_server:
    enabled: true
    timezones:
      - "UTC"
      - "America/New_York"
      - "Europe/London"

logging:
  level: "info"
  format: "json"