server:
  port: 8080
  host: "0.0.0.0"
  cors_enabled: true

nats:
  url: "nats://localhost:4222"
  jetstream:
    enabled: true
    retention_days: 7

database:
  path: "./data/hexarag.db"
  migrations_path: "./internal/adapters/storage/sqlite/migrations"

llm:
  provider: "openai-compatible"
  base_url: "http://localhost:11434/v1"  # Ollama default
  api_key: ""  # Set via HEXARAG_LLM_API_KEY env var if needed
  model: "deepseek-r1:8b"  # Default to deepseek-r1:8b
  max_tokens: 4096
  temperature: 0.7

tools:
  mcp_time_server:
    enabled: true
    timezones:
      - "UTC"
      - "America/New_York"
      - "Europe/London"
      - "Asia/Tokyo"

logging:
  level: "info"
  format: "json"